version: "3.6"
services:
  mongo:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo:/data/db"

  pyserver:
    container_name: processor_service
    image: pyserver:latest
    build: docker/processor_service
    volumes:
      - ./data_processor_service:/data_processor_service
    ports:
      - "8001:8000"
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo

  alert_monitor:
    container_name: monitor_service
    image: pyserver:latest
    build: docker/monitor_service
    volumes:
      - ./alerts_monitor_service:/alerts_monitor_service
    ports:
      - "8002:8000"
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
      - kafka

  handler_service:
    container_name: handler_service
    image: pyserver:latest
    build: docker/handler_service
    volumes:
      - ./alerts_handler_service:/alerts_handler_service
    ports:
      - "8003:8000"
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - kafka
      - mongo

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    depends_on:
      - mongo

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - mongo
      - zookeeper
