version: "3.6"
services:
  mongo:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo:/data/db"

  pyserver:
    env_file:
      - .env
    container_name: data_processor_service
    image: pyserver:latest
    build: .
    ports:
      - "8001:8000"
      - "8002:8000"
      - "8003:8000"
    environment:
      - MONGO_HOST=mongo

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181